#############################################################################
# Makefile for building: Astalasta
# Generated by qmake (2.01a) (Qt 4.8.5) on: Thu May 21 11:59:10 2015
# Project:  Astalasta.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Astalasta.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt/mkspecs/linux-g++ -I. -I/usr/lib64/qt/include/QtCore -I/usr/lib64/qt/include/QtGui -I/usr/lib64/qt/include -I. -IAstaClient -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib64/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt/lib -lQtGui -L/usr/lib64/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = AstaServer.cpp \
		Client.cpp \
		FinestraPuntata.cpp \
		AstaClient/AstaClient.cpp \
		AstaClient/FinestraLogin.cpp \
		AstaClient/FinestraNuovoOggetto.cpp \
		AstaClient/FinestraPrincipale.cpp \
		AstaClient/TestoTimer.cpp moc_FinestraPuntata.cpp \
		moc_FinestraLogin.cpp \
		moc_FinestraNuovoOggetto.cpp \
		moc_FinestraPrincipale.cpp \
		moc_TestoTimer.cpp
OBJECTS       = AstaServer.o \
		Client.o \
		FinestraPuntata.o \
		AstaClient.o \
		FinestraLogin.o \
		FinestraNuovoOggetto.o \
		FinestraPrincipale.o \
		TestoTimer.o \
		moc_FinestraPuntata.o \
		moc_FinestraLogin.o \
		moc_FinestraNuovoOggetto.o \
		moc_FinestraPrincipale.o \
		moc_TestoTimer.o
DIST          = /usr/lib64/qt/mkspecs/common/unix.conf \
		/usr/lib64/qt/mkspecs/common/linux.conf \
		/usr/lib64/qt/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt/mkspecs/common/g++-base.conf \
		/usr/lib64/qt/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt/mkspecs/qconfig.pri \
		/usr/lib64/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt/mkspecs/features/qt_config.prf \
		/usr/lib64/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt/mkspecs/features/default_pre.prf \
		/usr/lib64/qt/mkspecs/features/release.prf \
		/usr/lib64/qt/mkspecs/features/default_post.prf \
		/usr/lib64/qt/mkspecs/features/shared.prf \
		/usr/lib64/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt/mkspecs/features/warn_on.prf \
		/usr/lib64/qt/mkspecs/features/qt.prf \
		/usr/lib64/qt/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt/mkspecs/features/moc.prf \
		/usr/lib64/qt/mkspecs/features/resources.prf \
		/usr/lib64/qt/mkspecs/features/uic.prf \
		/usr/lib64/qt/mkspecs/features/yacc.prf \
		/usr/lib64/qt/mkspecs/features/lex.prf \
		/usr/lib64/qt/mkspecs/features/include_source_dir.prf \
		Astalasta.pro
QMAKE_TARGET  = Astalasta
DESTDIR       = 
TARGET        = Astalasta

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mascherinabrutta.h ui_mascherinabrutta2.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Astalasta.pro  /usr/lib64/qt/mkspecs/linux-g++/qmake.conf /usr/lib64/qt/mkspecs/common/unix.conf \
		/usr/lib64/qt/mkspecs/common/linux.conf \
		/usr/lib64/qt/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt/mkspecs/common/g++-base.conf \
		/usr/lib64/qt/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt/mkspecs/qconfig.pri \
		/usr/lib64/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib64/qt/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt/mkspecs/features/qt_config.prf \
		/usr/lib64/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt/mkspecs/features/default_pre.prf \
		/usr/lib64/qt/mkspecs/features/release.prf \
		/usr/lib64/qt/mkspecs/features/default_post.prf \
		/usr/lib64/qt/mkspecs/features/shared.prf \
		/usr/lib64/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt/mkspecs/features/warn_on.prf \
		/usr/lib64/qt/mkspecs/features/qt.prf \
		/usr/lib64/qt/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt/mkspecs/features/moc.prf \
		/usr/lib64/qt/mkspecs/features/resources.prf \
		/usr/lib64/qt/mkspecs/features/uic.prf \
		/usr/lib64/qt/mkspecs/features/yacc.prf \
		/usr/lib64/qt/mkspecs/features/lex.prf \
		/usr/lib64/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt/lib/libQtGui.prl \
		/usr/lib64/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile Astalasta.pro
/usr/lib64/qt/mkspecs/common/unix.conf:
/usr/lib64/qt/mkspecs/common/linux.conf:
/usr/lib64/qt/mkspecs/common/gcc-base.conf:
/usr/lib64/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt/mkspecs/common/g++-base.conf:
/usr/lib64/qt/mkspecs/common/g++-unix.conf:
/usr/lib64/qt/mkspecs/qconfig.pri:
/usr/lib64/qt/mkspecs/modules/qt_phonon.pri:
/usr/lib64/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/lib64/qt/mkspecs/features/qt_functions.prf:
/usr/lib64/qt/mkspecs/features/qt_config.prf:
/usr/lib64/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt/mkspecs/features/default_pre.prf:
/usr/lib64/qt/mkspecs/features/release.prf:
/usr/lib64/qt/mkspecs/features/default_post.prf:
/usr/lib64/qt/mkspecs/features/shared.prf:
/usr/lib64/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt/mkspecs/features/warn_on.prf:
/usr/lib64/qt/mkspecs/features/qt.prf:
/usr/lib64/qt/mkspecs/features/unix/thread.prf:
/usr/lib64/qt/mkspecs/features/moc.prf:
/usr/lib64/qt/mkspecs/features/resources.prf:
/usr/lib64/qt/mkspecs/features/uic.prf:
/usr/lib64/qt/mkspecs/features/yacc.prf:
/usr/lib64/qt/mkspecs/features/lex.prf:
/usr/lib64/qt/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt/lib/libQtGui.prl:
/usr/lib64/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Astalasta.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Astalasta1.0.0 || $(MKDIR) .tmp/Astalasta1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Astalasta1.0.0/ && $(COPY_FILE) --parents FinestraPuntata.h AstaClient/Dati.h AstaClient/FinestraLogin.h AstaClient/FinestraNuovoOggetto.h AstaClient/FinestraPrincipale.h AstaClient/TestoTimer.h .tmp/Astalasta1.0.0/ && $(COPY_FILE) --parents AstaServer.cpp Client.cpp FinestraPuntata.cpp AstaClient/AstaClient.cpp AstaClient/FinestraLogin.cpp AstaClient/FinestraNuovoOggetto.cpp AstaClient/FinestraPrincipale.cpp AstaClient/TestoTimer.cpp .tmp/Astalasta1.0.0/ && $(COPY_FILE) --parents AstaClient/mascherinabrutta.ui AstaClient/mascherinabrutta2.ui .tmp/Astalasta1.0.0/ && (cd `dirname .tmp/Astalasta1.0.0` && $(TAR) Astalasta1.0.0.tar Astalasta1.0.0 && $(COMPRESS) Astalasta1.0.0.tar) && $(MOVE) `dirname .tmp/Astalasta1.0.0`/Astalasta1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Astalasta1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_FinestraPuntata.cpp moc_FinestraLogin.cpp moc_FinestraNuovoOggetto.cpp moc_FinestraPrincipale.cpp moc_TestoTimer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_FinestraPuntata.cpp moc_FinestraLogin.cpp moc_FinestraNuovoOggetto.cpp moc_FinestraPrincipale.cpp moc_TestoTimer.cpp
moc_FinestraPuntata.cpp: FinestraPuntata.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) FinestraPuntata.h -o moc_FinestraPuntata.cpp

moc_FinestraLogin.cpp: AstaClient/FinestraLogin.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) AstaClient/FinestraLogin.h -o moc_FinestraLogin.cpp

moc_FinestraNuovoOggetto.cpp: AstaClient/FinestraNuovoOggetto.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) AstaClient/FinestraNuovoOggetto.h -o moc_FinestraNuovoOggetto.cpp

moc_FinestraPrincipale.cpp: AstaClient/TestoTimer.h \
		AstaClient/FinestraPrincipale.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) AstaClient/FinestraPrincipale.h -o moc_FinestraPrincipale.cpp

moc_TestoTimer.cpp: AstaClient/TestoTimer.h
	/usr/lib64/qt/bin/moc $(DEFINES) $(INCPATH) AstaClient/TestoTimer.h -o moc_TestoTimer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mascherinabrutta.h ui_mascherinabrutta2.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mascherinabrutta.h ui_mascherinabrutta2.h
ui_mascherinabrutta.h: AstaClient/mascherinabrutta.ui
	/usr/lib64/qt/bin/uic AstaClient/mascherinabrutta.ui -o ui_mascherinabrutta.h

ui_mascherinabrutta2.h: AstaClient/mascherinabrutta2.ui
	/usr/lib64/qt/bin/uic AstaClient/mascherinabrutta2.ui -o ui_mascherinabrutta2.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

AstaServer.o: AstaServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AstaServer.o AstaServer.cpp

Client.o: Client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Client.o Client.cpp

FinestraPuntata.o: FinestraPuntata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FinestraPuntata.o FinestraPuntata.cpp

AstaClient.o: AstaClient/AstaClient.cpp AstaClient/FinestraLogin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AstaClient.o AstaClient/AstaClient.cpp

FinestraLogin.o: AstaClient/FinestraLogin.cpp AstaClient/FinestraLogin.h \
		AstaClient/FinestraPrincipale.h \
		AstaClient/TestoTimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FinestraLogin.o AstaClient/FinestraLogin.cpp

FinestraNuovoOggetto.o: AstaClient/FinestraNuovoOggetto.cpp AstaClient/FinestraNuovoOggetto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FinestraNuovoOggetto.o AstaClient/FinestraNuovoOggetto.cpp

FinestraPrincipale.o: AstaClient/FinestraPrincipale.cpp AstaClient/FinestraPrincipale.h \
		AstaClient/TestoTimer.h \
		AstaClient/Dati.h \
		AstaClient/FinestraNuovoOggetto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FinestraPrincipale.o AstaClient/FinestraPrincipale.cpp

TestoTimer.o: AstaClient/TestoTimer.cpp AstaClient/TestoTimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TestoTimer.o AstaClient/TestoTimer.cpp

moc_FinestraPuntata.o: moc_FinestraPuntata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FinestraPuntata.o moc_FinestraPuntata.cpp

moc_FinestraLogin.o: moc_FinestraLogin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FinestraLogin.o moc_FinestraLogin.cpp

moc_FinestraNuovoOggetto.o: moc_FinestraNuovoOggetto.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FinestraNuovoOggetto.o moc_FinestraNuovoOggetto.cpp

moc_FinestraPrincipale.o: moc_FinestraPrincipale.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FinestraPrincipale.o moc_FinestraPrincipale.cpp

moc_TestoTimer.o: moc_TestoTimer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TestoTimer.o moc_TestoTimer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

